/*
بِسْمِ اللهِ الرَّحْمٰنِ الرَّحِيْمِ  ﷺ InshaAllah
*/

import type { Metadata } from "next";

import { redirect } from "next/navigation";


export const metadata: Metadata = {
  title: "My Portfolio Site",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <>Home</>
  );
}


